/*
    Copyright 2011 Silvio Wehner, Franziska Staake, Thomas Schulze
  
    This file is part of HIS.

    HIS is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    HIS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with HIS.  If not, see <http://www.gnu.org/licenses/>.
 
 */
package his.ui.views;

import his.HIS;
import his.model.Hardware;
import his.model.Manufacturers;
import his.model.providers.HardwareProvider;
import his.ui.validations.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Franziska Staake
 */
public class NewHardware extends javax.swing.JDialog {
    /** Creates new form NewHardware */
    Hardware parentHardware;
    
    public NewHardware(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        parentHardware = null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtWarrantyEnd = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        txtPurchaseDate = new javax.swing.JTextField();
        txtReferingTo = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboWarrantySpan = new javax.swing.JComboBox();
        txtHardwareName = new javax.swing.JTextField();
        txtWarrantySpan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtProductNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboPlace = new javax.swing.JComboBox();
        comboManufacturer = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        categoryDataTree = new his.ui.controls.CategoryData();

        setModal(true);
        setName("newHardwareDialog"); // NOI18N
        setResizable(false);

        jLabel8.setText("Garantiezeitraum");

        jLabel7.setText("Garantieende");

        txtWarrantyEnd.setEditable(false);
        txtWarrantyEnd.setToolTipText("Datumsformat: dd.mm.yyyy");
        txtWarrantyEnd.setInputVerifier(new IsEmptyOrValidDateValidator(this, txtWarrantyEnd, "ungültiges Datumsformat"));

        btnCancel.setText("Schließen");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        btnCancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelKeyPressed(evt);
            }
        });

        jLabel6.setText("Kaufdatum");

        btnCreate.setText("Anlegen");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        txtPurchaseDate.setToolTipText("Datumsformat: dd.mm.yyyy");

        txtReferingTo.setEditable(false);

        btnSearch.setText("Suchen");

        jLabel9.setText("Kategorie");

        jLabel5.setText("gehört zu");

        txtHardwareName.setInputVerifier(new NotEmptyValidator(this, txtHardwareName, "Gerätename darf nicht leer sein!"));

        txtWarrantySpan.setInputVerifier(new IsEmptyOrPositiveNumericIntegerValidator(this, txtWarrantySpan, "Nur positive ganzzahlige Zahlen erlaubt."));

        jLabel1.setText("Gerätename");

        txtProductNumber.setEditable(false);
        txtProductNumber.setFocusTraversalPolicyProvider(true);
        txtProductNumber.setInputVerifier(new NotEmptyValidator(this, txtProductNumber, "Produktnummer darf nicht leer sein!"));

        jLabel4.setText("Ort");

        jLabel3.setText("Produktnummer");

        jLabel2.setText("Hersteller");

        comboPlace.setFocusTraversalPolicyProvider(true);

        comboManufacturer.setFocusTraversalPolicyProvider(true);
        comboManufacturer.setInputVerifier(new NotEmptyValidator(this, comboManufacturer, "Es muss ein Hersteller ausgewählt werden!"));

        jSeparator1.setPreferredSize(new java.awt.Dimension(100, 2));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        categoryDataTree.setMaximumSize(new java.awt.Dimension(395, 147));
        categoryDataTree.setPreferredSize(new java.awt.Dimension(395, 147));
        jScrollPane1.setViewportView(categoryDataTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(btnCreate))
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(btnCancel))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(198, 198, 198))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboManufacturer, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHardwareName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtReferingTo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtPurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtWarrantySpan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboWarrantySpan, 0, 83, Short.MAX_VALUE))
                                    .addComponent(txtProductNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(btnSearch)
                                    .addComponent(comboPlace, 0, 121, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(173, 173, 173))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtWarrantyEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHardwareName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProductNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtReferingTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearch))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtWarrantySpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboWarrantySpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtWarrantyEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnCreate))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnCancel))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel(){
        // Fenster schließen
        this.setVisible(false);
    }
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        cancel();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelKeyPressed
        cancel();
    }//GEN-LAST:event_btnCancelKeyPressed
    
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // Validation und Hardware erstellen
        if(isDataValid() && createHardware()) {
            this.setVisible(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Das Formular enthält Fehler.\nHardware konnte nicht gespeichert werden.",
                    "Speichern fehlgeschlagen", JOptionPane.ERROR_MESSAGE | JOptionPane.OK_OPTION );
        }
    }//GEN-LAST:event_btnCreateActionPerformed
    
    private boolean createHardware() {
        HardwareProvider hardwareProvider = new HardwareProvider();
        Hardware hardware = new Hardware();
        
        SimpleDateFormat formatter = new SimpleDateFormat("dd.mm.yyyy");
        Date purchaseDate;
        
        try {
            purchaseDate = formatter.parse(txtPurchaseDate.getText().trim());
        } catch (ParseException ex) {
            HIS.getLogger().error(ex);
            return false;
        }
        
        hardware.setName(txtHardwareName.getText().trim());
        hardware.setInventoryNumber(txtProductNumber.getText().trim());
        hardware.setPurchaseDate(purchaseDate);
        // TODO: CreateOrGetManufacturer
        hardware.setManufacturer(null);
        
        if(!comboPlace.getSelectedItem().toString().trim().isEmpty()) {
            // TODO: CreateOrGetPlace
            hardware.setPlace(null);
        }
        
        if(!txtWarrantyEnd.getText().trim().isEmpty()) {
            try {
                Date warrantyEnd = formatter.parse(txtWarrantyEnd.getText().trim());
                hardware.setWarrantyEnd(warrantyEnd);
            } catch (ParseException ex) {
                HIS.getLogger().debug(ex);
            }
        }
        
        hardware.setHardware(parentHardware);
        
        try {
            hardwareProvider.create(hardware);
        }
        catch (Exception e) {
            HIS.getLogger().debug(e);
            HIS.getLogger().warn("Speichern der Hardware fehlgeschlagen.");
            return false;
        }
        
        return true;
    }
    
    private boolean isDataValid() {
        boolean isDataValid = true;
        isDataValid = this.txtHardwareName.getInputVerifier().verify(txtHardwareName);
        isDataValid = this.txtProductNumber.getInputVerifier().verify(txtProductNumber) && isDataValid;
        isDataValid = this.txtPurchaseDate.getInputVerifier().verify(txtPurchaseDate) && isDataValid;
        isDataValid = this.comboManufacturer.getInputVerifier().verify(comboManufacturer) && isDataValid;
        isDataValid = this.txtWarrantyEnd.getInputVerifier().verify(txtWarrantyEnd) && isDataValid;
        isDataValid = this.txtWarrantySpan.getInputVerifier().verify(txtWarrantySpan) && isDataValid;
        return isDataValid;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            HIS.getLogger().error(ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NewHardware dialog = new NewHardware(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnSearch;
    private his.ui.controls.CategoryData categoryDataTree;
    private javax.swing.JComboBox comboManufacturer;
    private javax.swing.JComboBox comboPlace;
    private javax.swing.JComboBox comboWarrantySpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtHardwareName;
    private javax.swing.JTextField txtProductNumber;
    private javax.swing.JTextField txtPurchaseDate;
    private javax.swing.JTextField txtReferingTo;
    private javax.swing.JTextField txtWarrantyEnd;
    private javax.swing.JTextField txtWarrantySpan;
    // End of variables declaration//GEN-END:variables
    
}
