/*
    Copyright 2011 Silvio Wehner, Franziska Staake, Thomas Schulze
  
    This file is part of HIS.

    HIS is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    HIS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with HIS.  If not, see <http://www.gnu.org/licenses/>.
 
 */
package his.ui.controls;

import his.business.CategoryResultBusiness;
import his.model.Categories;
import his.ui.events.ResultShowEvent;
import his.ui.events.ResultShowListener;
import javax.swing.DefaultListModel;

/**
 *
 * @author Franziska Staake, Thomas Schulze
 */
public class CategoryResult extends javax.swing.JPanel {
    private CategoryResultBusiness catResultBusiness;
    private Categories selectedCategories;
    /** Creates new form UserResult */
    public CategoryResult() {
        initComponents();
    }  
    
    protected javax.swing.event.EventListenerList resultShowListenerList =
        new javax.swing.event.EventListenerList();

    public void addCategoriesResultShowListener(ResultShowListener listener) {
        resultShowListenerList.add(ResultShowListener.class, listener);
    }

    public void removeCategoriesResultShowListener(ResultShowListener listener) {
        resultShowListenerList.remove(ResultShowListener.class, listener);
    }

    void fireCategoriesResultShow(ResultShowEvent evt) {
        Object[] listeners = resultShowListenerList.getListenerList();
        // Each listener occupies two elements - the first is the listener class
        // and the second is the listener instance
        for (int i=0; i<listeners.length; i+=2) {
            if (listeners[i]==ResultShowListener.class) {
                ((ResultShowListener)listeners[i+1]).categoriesResultShowPerfomed(evt);
            }
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstResult = new javax.swing.JList();

        lstResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lstResultMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(lstResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lstResultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstResultMousePressed
       selectedCategories = (Categories)lstResult.getSelectedValue();
        fireCategoriesResultShow(new ResultShowEvent(this));
    }//GEN-LAST:event_lstResultMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstResult;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the catResultBusiness
     */
    public CategoryResultBusiness getCatResultBusiness() {
        return catResultBusiness;
    }

    /**
     * @param catResultBusiness the catResultBusiness to set
     */
    public void setCatResultBusiness(CategoryResultBusiness catResultBusiness) {
        this.catResultBusiness = catResultBusiness;
        showResults();
    }

    private void showResults() {
        DefaultListModel model = new DefaultListModel();
        
        for(Categories cat: catResultBusiness.getCategories())
            model.addElement(cat);
        
        lstResult.setModel(model);
    }

    /**
     * @return the selectedCategories
     */
    public Categories getSelectedCategory() {
        return selectedCategories;
    }
}
